---
kind: pipeline
name: RPM Build EL7

platform:
  os: linux
  arch: amd64

steps:
- name: Build RPM EL7
  image: centos:7
  commands:
  - policy/centos7/scripts/build

- name: Sign RPM EL7
  image: centos:7
  environment:
    PRIVATE_KEY:
      from_secret: private_key
    PRIVATE_KEY_PASS_PHRASE:
      from_secret: private_key_pass_phrase
    TESTING_PRIVATE_KEY:
      from_secret: testing_private_key
    TESTING_PRIVATE_KEY_PASS_PHRASE:
      from_secret: testing_private_key_pass_phrase
  commands:
  - policy/centos7/scripts/sign
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

- name: Create repo metadata for EL7
  image: centos:7
  commands:
  - policy/centos7/scripts/repo-metadata

- name: Upload RPM EL7
  image: centos:7
  environment:
    AWS_S3_BUCKET:
      from_secret: aws_s3_bucket
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access_key_id
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret_access_key
    TESTING_AWS_S3_BUCKET:
      from_secret: testing_aws_s3_bucket
    TESTING_AWS_ACCESS_KEY_ID:
      from_secret: testing_aws_access_key_id
    TESTING_AWS_SECRET_ACCESS_KEY:
      from_secret: testing_aws_secret_access_key
  commands:
  - policy/centos7/scripts/upload-repo
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

- name: GitHub Release RPM EL7
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    prerelease: true
    checksum:
    - sha256
    checksum_file: CHECKSUMsum-centos7-noarch.txt
    checksum_flatten: true
    files:
    - "policy/centos7/dist/**/*.rpm"
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag
---
kind: pipeline
name: RPM Build EL8

platform:
  os: linux
  arch: amd64

steps:
- name: Build RPM EL8
  image: quay.io/centos/centos:stream8
  commands:
  - policy/centos8/scripts/build

- name: Sign RPM EL8 (dry-run)
  image: quay.io/centos/centos:stream8
  commands:
  - policy/centos8/scripts/sign --dry-run
  when:
    event:
    - pull_request

- name: Sign RPM EL8
  image: quay.io/centos/centos:stream8
  environment:
    PRIVATE_KEY:
      from_secret: private_key
    PRIVATE_KEY_PASS_PHRASE:
      from_secret: private_key_pass_phrase
    TESTING_PRIVATE_KEY:
      from_secret: testing_private_key
    TESTING_PRIVATE_KEY_PASS_PHRASE:
      from_secret: testing_private_key_pass_phrase
  commands:
  - policy/centos8/scripts/sign
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

- name: Create repo metadata for EL8
  image: quay.io/centos/centos:stream8
  commands:
  - policy/centos8/scripts/repo-metadata

- name: Yum Repo Upload RPM EL8
  image: quay.io/centos/centos:stream8
  environment:
    AWS_S3_BUCKET:
      from_secret: aws_s3_bucket
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access_key_id
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret_access_key
    TESTING_AWS_S3_BUCKET:
      from_secret: testing_aws_s3_bucket
    TESTING_AWS_ACCESS_KEY_ID:
      from_secret: testing_aws_access_key_id
    TESTING_AWS_SECRET_ACCESS_KEY:
      from_secret: testing_aws_secret_access_key
  commands:
  - policy/centos8/scripts/upload-repo
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

- name: GitHub Release RPM EL8
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    prerelease: true
    checksum:
    - sha256
    checksum_file: CHECKSUMsum-centos8-noarch.txt
    checksum_flatten: true
    files:
    - "policy/centos8/dist/**/*.rpm"
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

---
kind: pipeline
name: RPM Build EL9

platform:
  os: linux
  arch: amd64

steps:
- name: Build RPM EL9
  image: quay.io/centos/centos:stream9
  commands:
  - policy/centos9/scripts/build

- name: Sign RPM EL9 (dry-run)
  image: quay.io/centos/centos:stream9
  commands:
  - policy/centos9/scripts/sign --dry-run
  when:
    event:
    - pull_request

- name: Sign RPM EL9
  image: quay.io/centos/centos:stream9
  environment:
    PRIVATE_KEY:
      from_secret: private_key
    PRIVATE_KEY_PASS_PHRASE:
      from_secret: private_key_pass_phrase
    TESTING_PRIVATE_KEY:
      from_secret: testing_private_key
    TESTING_PRIVATE_KEY_PASS_PHRASE:
      from_secret: testing_private_key_pass_phrase
  commands:
  - policy/centos9/scripts/sign
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

- name: Create repo metadata for EL9
  image: quay.io/centos/centos:stream9
  commands:
  - policy/centos9/scripts/repo-metadata

- name: Upload RPM EL9
  image: quay.io/centos/centos:stream9
  environment:
    AWS_S3_BUCKET:
      from_secret: aws_s3_bucket
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access_key_id
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret_access_key
    TESTING_AWS_S3_BUCKET:
      from_secret: testing_aws_s3_bucket
    TESTING_AWS_ACCESS_KEY_ID:
      from_secret: testing_aws_access_key_id
    TESTING_AWS_SECRET_ACCESS_KEY:
      from_secret: testing_aws_secret_access_key
  commands:
  - policy/centos9/scripts/upload-repo
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

- name: GitHub Release RPM EL9
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    prerelease: true
    checksum:
    - sha256
    checksum_file: CHECKSUMsum-centos9-noarch.txt
    checksum_flatten: true
    files:
    - "policy/centos9/dist/**/*.rpm"
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

---
kind: pipeline
name: RPM Build MicroOS

platform:
  os: linux
  arch: amd64

steps:
- name: Build RPM MicroOS
  image: opensuse/tumbleweed
  commands:
  - policy/microos/scripts/build

- name: Sign RPM MicroOS (dry-run)
  image: opensuse/tumbleweed
  commands:
  - policy/microos/scripts/sign --dry-run
  when:
    event:
    - pull_request

- name: Sign RPM MicroOS
  image: opensuse/tumbleweed
  environment:
    PRIVATE_KEY:
      from_secret: private_key
    PRIVATE_KEY_PASS_PHRASE:
      from_secret: private_key_pass_phrase
    TESTING_PRIVATE_KEY:
      from_secret: testing_private_key
    TESTING_PRIVATE_KEY_PASS_PHRASE:
      from_secret: testing_private_key_pass_phrase
  commands:
  - policy/microos/scripts/sign
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

- name: Create repo metadata for Microos
  image: opensuse/tumbleweed
  commands:
  - policy/microos/scripts/repo-metadata

- name: Yum Repo Upload RPM MicroOS
  image: opensuse/tumbleweed
  environment:
    AWS_S3_BUCKET:
      from_secret: aws_s3_bucket
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access_key_id
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret_access_key
    TESTING_AWS_S3_BUCKET:
      from_secret: testing_aws_s3_bucket
    TESTING_AWS_ACCESS_KEY_ID:
      from_secret: testing_aws_access_key_id
    TESTING_AWS_SECRET_ACCESS_KEY:
      from_secret: testing_aws_secret_access_key
  commands:
  - policy/microos/scripts/upload-repo
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

- name: GitHub Release RPM MicroOS
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    prerelease: true
    checksum:
    - sha256
    checksum_file: CHECKSUMsum-microos-noarch.txt
    checksum_flatten: true
    files:
    - "policy/microos/dist/**/*.rpm"
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

---
kind: pipeline
name: RPM Build Fedora37

platform:
  os: linux
  arch: amd64

steps:
- name: Build RPM Fedora37
  image: fedora:40
  commands:
  - policy/fedora37/scripts/build

- name: Sign RPM Fedora37 (dry-run)
  image: fedora:40
  commands:
  - policy/fedora37/scripts/sign --dry-run
  when:
    event:
    - pull_request

- name: Sign RPM Fedora37
  image: fedora:40
  environment:
    PRIVATE_KEY:
      from_secret: private_key
    PRIVATE_KEY_PASS_PHRASE:
      from_secret: private_key_pass_phrase
    TESTING_PRIVATE_KEY:
      from_secret: testing_private_key
    TESTING_PRIVATE_KEY_PASS_PHRASE:
      from_secret: testing_private_key_pass_phrase
  commands:
  - policy/fedora37/scripts/sign
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

- name: Create repo metadata for Fedora37
  image: fedora:40
  commands:
  - policy/fedora37/scripts/repo-metadata

- name: Yum Repo Upload Fedora37
  image: fedora:40
  environment:
    AWS_S3_BUCKET:
      from_secret: aws_s3_bucket
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access_key_id
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret_access_key
    TESTING_AWS_S3_BUCKET:
      from_secret: testing_aws_s3_bucket
    TESTING_AWS_ACCESS_KEY_ID:
      from_secret: testing_aws_access_key_id
    TESTING_AWS_SECRET_ACCESS_KEY:
      from_secret: testing_aws_secret_access_key
  commands:
  - policy/fedora37/scripts/upload-repo
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

- name: GitHub Release Fedora37
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    prerelease: true
    checksum:
    - sha256
    checksum_file: CHECKSUMsum-fedora37-noarch.txt
    checksum_flatten: true
    files:
    - "policy/fedora37/dist/**/*.rpm"
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag
