#!/bin/bash
set -e -x

DIRS=("noarch" "source")

cd $(dirname $0)/..
. ./scripts/version

zypper install -y createrepo_c

for dir in "${DIRS[@]}"; do
	echo "Creating repository metadata for $dir"
	createrepo_c "dist/$dir/"
done

