#!/bin/bash
set -eo pipefail

BASE_DIR="build"

function usage(){
    echo "$0 <policy>"
    exit 1
}

function check_input(){
    policy=$1
    if [[ ! -d "${BASE_DIR}/${policy}" ]]; then
        echo "Policy ${policy} not found, run make build and try again."
        exit 2
    fi
    
    [ -z "${TAG}" ] && echo "TAG is not set." && exit 1
    return 0
}

function checksum_file(){
    policy=$1

    sumfile="${BASE_DIR}/${policy}/sha256sum-${policy}-noarch.txt"
    echo -n "" > "${sumfile}"

    files=$(ls build/"${policy}"/**/*.rpm)
    for file in ${files}; do
      sha256sum "${file}" | sed "s;$(dirname ${file})/;;g" >> "${sumfile}"
    done

    cat "${sumfile}"
}

function upload_files(){
    policy=$1
    
    files=("${BASE_DIR}/${policy}/sha256sum-${policy}-noarch.txt ")
    files+=$(ls build/"${policy}"/**/*.rpm)

    for file in ${files}; do
        gh release upload ${TAG} $file
    done
}

function main()
{
    check_input "$1"
    checksum_file "$1"
    upload_files "$1"
}

[[ -z "$1" ]] && usage

main "$1"
