name: E2E Tests

on:
  push:
    paths:
      - 'policy/**'
      - 'hack/**'
      - 'Dockerfile'
      - 'Makefile'
  pull_request:
    paths:
      - 'policy/**'
      - 'hack/**'
      - 'Dockerfile'
      - 'Makefile'

permissions:
  contents: read

env:
  LIMA_VERSION: v2.1.0
  LIMA_SHA256: 9e52c605790649aceac1f894eb2bb7cdb45897257faafb54ff30ce6a576bebfa
  LIMA_GUESTAGENTS_SHA256: f77730b5295e03f4cb4bfb8eeb3661fdde6c592a33bae4a2a68cecc03a93da8a

jobs:
  e2e:
    strategy:
      matrix:
        distro: [centos9, centos10, fedora42, microos]

    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

    # https://lima-vm.io/docs/examples/gha/
    - name: Install QEMU
      run: |
        set -eux
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends ovmf qemu-system-x86 qemu-utils
        sudo modprobe kvm
        sudo chown $(whoami) /dev/kvm

    - name: Install Lima
      run: |
        set -eux
        LIMA_FILE="lima-${LIMA_VERSION:1}-$(uname -s)-$(uname -m).tar.gz"
        AGENTS_FILE="lima-additional-guestagents-${LIMA_VERSION:1}-$(uname -s)-$(uname -m).tar.gz"
        
        curl -fsSLO "https://github.com/lima-vm/lima/releases/download/${LIMA_VERSION}/${LIMA_FILE}"
        curl -fsSLO "https://github.com/lima-vm/lima/releases/download/${LIMA_VERSION}/${AGENTS_FILE}"

        echo "${LIMA_SHA256}  ${LIMA_FILE}" | sha256sum -c -
        echo "${LIMA_GUESTAGENTS_SHA256}  ${AGENTS_FILE}" | sha256sum -c -

        sudo tar Cxzvm /usr/local -f "${LIMA_FILE}"
        sudo tar Cxzvm /usr/local -f "${AGENTS_FILE}"

    - name: Cache ~/.cache/lima
      uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
      with:
        path: ~/.cache/lima
        key: lima-${{ env.LIMA_VERSION }}

    - name: E2E ${{ matrix.distro }}
      run: make e2e-${{ matrix.distro }}
